- name : filewala demo
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    - mypath: /home/ec2-user/sample.txt
    - dirpath: /home/ec2-user/myfolder
  tasks:
     - name: craete file
       file:
          path: "{{mypath}}"
          state: touch
     - name: craete directory
       file:
          path: "{{dirpath}}"
          state: directory
